flowchart TD

    subgraph Input
        A[User Preferences<br/>Genre, Mood, Energy level]
        B[Ranking of Genre, Mood, Energy]
    end

    subgraph Application
        C[Streamlit App - app.py]
        D[Python Backend]
        E[Weights get assigned, Preferences are returned in a prompt]
    end

    subgraph AI_System
        F[Gemini API Agent]
        G[(Song Dataset)]
    end

    subgraph Output
        H[Top 5 Ranked Songs]
    end

    subgraph Evaluation
        I[User Reviews Results]
    end

    A --> C
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
    G --> H
    H --> I
    I -. Can regenerate .-> F